# Generated by Django 4.2.16 on 2024-10-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity_in_grams',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
