# Generated by Django 4.2.16 on 2024-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_food_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned_per_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
