# Generated by Django 4.2.16 on 2024-10-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_exercise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrecord',
            old_name='foodrecord',
            new_name='food',
        ),
    ]
