# Generated by Django 4.2.16 on 2024-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_foodrecord_foodrecord_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
