# Generated by Django 4.2.16 on 2024-10-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_user_info_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.userprofile'),
        ),
    ]
